spring:

  datasource:
    driver-class-name: org.h2.Driver #h2 드라이버
    url: jdbc:h2:~/sharemore #DB 파일 저장 경로 (임베디드 모드)
    username: sa
    password:

  h2:
    console:
      enabled: true #h2-console 사용 여부docker-compose.yml
      path: /h2-console #h2-console 접근 경로

  jpa:
    hibernate:
      ddl-auto: create #테이블 자동 생성
    properties:
      hibernate:
        format_sql: true #쿼리 출력
        show_sql: true #쿼리 출력
    defer-datasource-initialization: true

  rabbitmq:
    host: localhost
    port: 5672
    # username: guest
    # password: guest
    username: junwoo # 3. admin, vhost 추가한 경우
    password: junwoo # 3. admin, vhost 추가한 경우
    virtual-host: junwoo # 3. admin, vhost 추가한 경우

  redis:
    host: localhost
    port: 6379



  sql:
    init:
      mode: always

logging:
  level:
    root: info

jwt:
  secret: ThisIsTestKeyThisIsTestKeyThisIsTestKeyThisIsTestKeyThisIsTestKeyThisIsTestKey